spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://localhost:8001
        predicates:
        - Path=/api/user/v1/**
      - id: category-service
        uri: http://localhost:8002
        predicates:
        - Path=/api/cat/v1/**
      - id: product-service
        uri: http://localhost:8003
        predicates:
        - Path=/api/product/v1/**
      - id: order-service
        uri: http://localhost:8004
        predicates:
        - Path=/api/user/v1/**
      - id: cart-service
        uri: http://localhost:8005
        predicates:
        - Path=/api/cart/v1/**
          
server:
  port: 8085
  
eureka:
  instance:
    appName: gateway-service
    hostname: localhost
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS